### ISSUE TITLE
Minor: Adhearsion falsely warns that custom environments aren't supported

### ISSUE THREAD

**Issue by sfgeorge** [adhearsion/adhearsion#442]
FYI This is a cosmetic issue.  Functionally I have exactly what I want (running a custom environment name), I just figured we can tighten the logging to not falsely report warnings.

I have an application uses the following:

Ruby:  jruby-1.7.4

Gems
* Adhearsion v2.5.0
* Rails 3.2.12

Pertinent environment variables
* RAILS_ENV=integration
* AHN_ENV=integration
* AHN_PLATFORM_ENVIRONMENT=integration

Startup procedure
    <ENV variables> rvm jruby-1.7.4 exec bundle exec ahn start .

#### Observed behavior:

The log messages in adhearsion.log tell conflicting stories...

    You tried to initialize with an invalid environment name integration. Valid values are [:production, :development, :staging, :test].
    ...
    [2014-02-20 18:08:20.026] INFO  Adhearsion::Initializer: Adhearsion v2.5.0 initialized in "integration"!

The interesting thing is that both [message 1](https://github.com/adhearsion/adhearsion/blob/v2.5.0/lib/adhearsion.rb#L76-L79) and [message 2](https://github.com/adhearsion/adhearsion/blob/v2.5.0/lib/adhearsion/initializer.rb#L70) are talking about the same configuration variable, `config.platform.environment`.

_Additionally, the first message is logged to STDOUT, which made it hard for me to discover it._

**Comment by benlangfeld** [comment]
See also https://github.com/adhearsion/adhearsion/pull/574, which removes `AHN_PLATFORM_ENVIRONMENT`, using only `AHN_ENV`. Still, though, we require you to use one of the defined environments. This is, as @bklang says, because top level config keys need to be declared. You could equally create a plugin whose config key is `integration` like so:

```ruby
class MyPlugin < Adhearsion::Plugin
  config :integration do
    foo :bar
  end
end
```

and then set the value using `config.integration.foo.bar = :baz`. If you were to set this value in the development environment only, it would be: `config.development.integration.foo.bar = :baz`.

As you can see, with this syntax, Adhearsion's only way of differentiating between environment names and plugin named as the top level key is by registration, which for environment names is hard-coded in Adhearsion.

We could potentially deal with this by introducing a different syntax for declaring config per-environment, such as `config.env(:production).foo.bar`. This would mean that top-level config keys were no longer used for specifying config per-environment, and as such we could support any environment name you wish.

Does this option sound like a good way forward? It would have the beneficial side-effect of simplifying the `Adhearsion::Configuration` code a little bit, with the downside being that it would not be backwards compatible.

**Comment by bklang** [comment]
> We could potentially deal with this by introducing a different syntax for declaring config per-environment, such as config.env(:production).foo.bar. This would mean that top-level config keys were no longer used for specifying config per-environment, and as such we could support any environment name you wish.

For me, I like this idea.  Sounds like a good approach for Adhearsion3

**Comment by sfgeorge** [comment]
> For what purpose (other than Rails integration) does the name of your application's environment matter? If rails is the problem, you can simply set RAILS_ENV and Adhearsion won't care.

Very good point!  I assumed my bind was in that I needed to control RAILS_ENV.   And I incorrectly assumed Adhearsion would restrict my ability to do so.  The fact that RAILS_ENV can be changed independently from Adhearsion prevents coupling and solves my self-made problem. :)

I also appreciate the Plugin workaround available immediately.  While that would require knowing the environment (e.g. `MyPlugin.config.send(my_env).foo`), it still is a reasonable way for now.

> We could potentially deal with this by introducing a different syntax for declaring config per-environment, such as `config.env(:production).foo.bar`. This would mean that top-level config keys were no longer used for specifying config per-environment, and as such we could support any environment name you wish.

I like this idea too for Adhearsion 3!  This is great.  I assume that would allow me to later access the config value within the app as `config.foo`, agnostic of which environment I'm in.  This is awesome!

**Comment by benlangfeld** [comment]
Closing in favour of https://github.com/adhearsion/adhearsion/pull/577
