### ISSUE TITLE
Introduce application "plugins"

### ISSUE THREAD

**Issue by benlangfeld** [adhearsion/adhearsion#566]
For app-specific configuration and initializers

**Comment by bklang** [comment]
Right now, I've seen few conventions:

`app/plugin.rb` - but an app isn't a plugin
`app/app.rb` - feels a bit redundant
`lib/app.rb` - but you should not keep application-specific code in `/lib`

What about doing config/app.rb? This makes some sense to me because the most common reason for having this is to provide for application-specific configuration.

**Comment by benlangfeld** [comment]
Closing in favour of https://github.com/adhearsion/adhearsion/pull/578
